
import type { Guest } from '@/types';
import { add, format, sub } from 'date-fns';

export const guests = (): Guest[] => {
  const today = new Date();

  return [
    {
      id: 'guest-1',
      name: 'Eleanor Vance',
      email: 'eleanor.v@example.com',
      phone: '555-0101',
      status: 'Checked-in',
      source: 'PANstrat',
      totalStays: 3,
      loyaltyTier: 'Gold',
      age: 42,
      occupation: 'Architect',
      homeTown: 'London, UK',
      language: 'English',
      gender: 'Female',
      dateOfBirth: '1982-03-15',
      stayHistory: [
        {
          hotelName: 'Last Word Franschhoek',
          checkInDate: '2023-08-15',
          checkOutDate: '2023-08-20',
          roomNumber: '12',
          partySize: 2,
        },
        {
          hotelName: 'Last Word Kitara',
          checkInDate: '2023-12-22',
          checkOutDate: '2023-12-26',
          roomNumber: '05',
          partySize: 2,
        },
        {
          hotelName: 'Last Word Madikwe',
          checkInDate: format(sub(today, { days: 2 }), 'yyyy-MM-dd'),
          checkOutDate: format(add(today, { days: 3 }), 'yyyy-MM-dd'),
          roomNumber: '15',
          partySize: 2,
          children: 0,
          pets: false,
        },
      ],
      preferences: `Prefers sparkling water in the room.
Celebrated their anniversary with us last year.
Likes a dinner reservation made for 8 PM on the first night.`,
      onSiteActivity: {
        firstSeen: format(sub(today, { days: 2, hours: 3 }), 'yyyy-MM-dd, HH:mm'),
        lastSeen: format(sub(today, { hours: 1 }), 'yyyy-MM-dd, HH:mm'),
        connectedDevices: ['iPhone 15 Pro', 'MacBook Air'],
        venuesVisited: ['Madikwe Lodge', 'Franschhoek Pool Bar'],
      },
      communicationHistory: [
          { date: '2023-12-27', log: 'Post-stay "Thank You" email sent.'},
          { date: '2023-08-21', log: 'Post-stay "Thank You" email sent.'}
      ],
      feedback: [
        { date: '2023-12-27', type: 'Review', source: 'Email', content: '"Absolutely loved the safari at Kitara. The guide was exceptional."' },
        { date: '2023-08-20', type: 'Comment', source: 'Front Desk', content: 'Mentioned that the wifi in room 12 was a bit slow in the evening.' },
      ]
    },
    {
      id: 'guest-2',
      name: 'Marcus Thorne',
      email: 'm.thorne@example.com',
      phone: '555-0102',
      status: 'Arriving Soon',
      source: 'Booking.com',
      totalStays: 1,
      loyaltyTier: 'Member',
      age: 35,
      occupation: 'Photographer',
      homeTown: 'New York, USA',
      language: 'English',
      gender: 'Male',
      dateOfBirth: '1989-06-21',
      stayHistory: [
        {
          hotelName: 'Last Word Franschhoek',
          checkInDate: format(add(today, { days: 1 }), 'yyyy-MM-dd'),
          checkOutDate: format(add(today, { days: 5 }), 'yyyy-MM-dd'),
          roomNumber: '07',
          partySize: 1,
          children: 0,
          pets: false,
        },
      ],
      preferences: 'First time guest. Interested in local wine tours.',
      onSiteActivity: {
        firstSeen: 'N/A',
        lastSeen: 'N/A',
        connectedDevices: [],
      },
      communicationHistory: [
          { date: format(sub(today, {days: 7}), 'yyyy-MM-dd'), log: 'Pre-stay "Looking forward to your visit" email sent.'}
      ],
      feedback: []
    },
    {
      id: 'guest-3',
      name: 'Seraphina Dubois',
      email: 'seraphina.d@example.com',
      phone: '555-0103',
      status: 'Checked-out',
      source: 'PANstrat',
      totalStays: 2,
      loyaltyTier: 'Platinum',
      age: 51,
      occupation: 'Art Curator',
      homeTown: 'Paris, France',
      language: 'French, English',
      gender: 'Female',
      dateOfBirth: '1973-01-25',
      stayHistory: [
          {
              hotelName: 'Last Word Kalahari',
              checkInDate: '2024-01-10',
              checkOutDate: '2024-01-18',
              roomNumber: 'Suite 01',
              partySize: 2
          },
          {
              hotelName: 'Last Word Constantia',
              checkInDate: format(sub(today, { days: 10 }), 'yyyy-MM-dd'),
              checkOutDate: format(sub(today, { days: 5 }), 'yyyy-MM-dd'),
              roomNumber: 'Suite 02',
              partySize: 2
          },
      ],
      preferences: `Always requests a room with a garden view.
Prefers champagne on arrival.`,
      onSiteActivity: {
        firstSeen: format(sub(today, { days: 10, hours: 2 }), 'yyyy-MM-dd, HH:mm'),
        lastSeen: format(sub(today, { days: 5, hours: 1 }), 'yyyy-MM-dd, HH:mm'),
        connectedDevices: ['iPhone 14', 'iPad Pro'],
      },
      communicationHistory: [
        { date: format(sub(today, { days: 4 }), 'yyyy-MM-dd'), log: "Post-stay 'Thank You' email sent." },
        { date: '2024-01-19', log: "Post-stay 'Thank You' email sent." },
      ],
      feedback: [
          { date: '2024-01-19', type: 'Review', source: 'TripAdvisor', content: '"The tranquility of the Kalahari property is unmatched. A truly luxurious escape."' },
      ]
    },
    {
      id: 'guest-4',
      name: 'Liam O\'Connell',
      email: 'liam.oc@example.com',
      phone: '555-0104',
      status: 'Checked-in',
      source: 'Booking.com',
      totalStays: 5,
      loyaltyTier: 'Platinum',
      age: 48,
      occupation: 'Journalist',
      homeTown: 'Dublin, Ireland',
      language: 'English',
      gender: 'Male',
      dateOfBirth: '1976-11-05',
      stayHistory: [
        {
          hotelName: 'Last Word Kitara',
          checkInDate: format(sub(today, { days: 1 }), 'yyyy-MM-dd'),
          checkOutDate: format(add(today, { days: 6 }), 'yyyy-MM-dd'),
          roomNumber: '08',
          partySize: 1,
        },
      ],
      preferences: 'Avid bird watcher. Requests binoculars and a local guide book.',
      onSiteActivity: {
        firstSeen: format(sub(today, { days: 1, hours: 5 }), 'yyyy-MM-dd, HH:mm'),
        lastSeen: format(sub(today, { minutes: 30 }), 'yyyy-MM-dd, HH:mm'),
        connectedDevices: ['Pixel 8 Pro'],
      },
      communicationHistory: [
        { date: format(sub(today, { days: 10 }), 'yyyy-MM-dd'), log: 'Booking confirmation for safari tour.' },
      ],
      feedback: []
    },
    {
      id: 'guest-5',
      name: 'Sofia Rossi',
      email: 'sofia.r@example.com',
      phone: '555-0105',
      status: 'Arriving Soon',
      source: 'Manual Entry',
      totalStays: 2,
      loyaltyTier: 'Gold',
      age: 33,
      occupation: 'Chef',
      homeTown: 'Florence, Italy',
      language: 'Italian, English',
      gender: 'Female',
      dateOfBirth: '1991-09-12',
      stayHistory: [
        {
          hotelName: 'Last Word Long Beach',
          checkInDate: '2023-07-20',
          checkOutDate: '2023-07-25',
          roomNumber: '301',
          partySize: 2,
        },
        {
          hotelName: 'Last Word Constantia',
          checkInDate: format(add(today, { days: 3 }), 'yyyy-MM-dd'),
          checkOutDate: format(add(today, { days: 8 }), 'yyyy-MM-dd'),
          roomNumber: '11',
          partySize: 2,
          children: 0,
          pets: true,
        },
      ],
      preferences: 'Requires hypoallergenic bedding. Enjoys white wine, preferably Sauvignon Blanc.',
      onSiteActivity: {
        firstSeen: 'N/A',
        lastSeen: 'N/A',
        connectedDevices: [],
      },
      communicationHistory: [
        { date: format(sub(today, { days: 4 }), 'yyyy-MM-dd'), log: 'Confirmed dinner reservations via email.' },
      ],
      feedback: [
        { date: '2023-07-26', type: 'Complaint', source: 'Front Desk', content: 'Air conditioning unit in room 301 was noisy. Offered complimentary breakfast.'}
      ]
    },
    {
      id: 'guest-6',
      name: 'Kenji Tanaka',
      email: 'kenji.t@example.com',
      phone: '555-0106',
      status: 'Checked-out',
      source: 'Booking.com',
      totalStays: 1,
      loyaltyTier: 'Member',
      age: 28,
      occupation: 'Software Engineer',
      homeTown: 'Tokyo, Japan',
      language: 'Japanese, English',
      gender: 'Male',
      dateOfBirth: '1996-04-30',
      stayHistory: [
        {
          hotelName: 'Last Word Long Beach',
          checkInDate: format(sub(today, { days: 8 }), 'yyyy-MM-dd'),
          checkOutDate: format(sub(today, { days: 3 }), 'yyyy-MM-dd'),
          roomNumber: '105',
          partySize: 1,
        },
      ],
      preferences: 'Interested in surfing lessons. Requested a late check-out.',
      onSiteActivity: {
        firstSeen: format(sub(today, { days: 8 }), 'yyyy-MM-dd, HH:mm'),
        lastSeen: format(sub(today, { days: 3 }), 'yyyy-MM-dd, HH:mm'),
        connectedDevices: ['Samsung Galaxy S23'],
      },
      communicationHistory: [
        { date: format(sub(today, { days: 2 }), 'yyyy-MM-dd'), log: 'Post-stay survey sent.' },
      ],
      feedback: [
        { date: format(sub(today, {days: 2}), 'yyyy-MM-dd'), type: 'Suggestion', source: 'Survey', content: 'Suggests offering a shuttle service to popular surfing spots.'}
      ]
    },
    {
      id: 'guest-7',
      name: 'Ava Chen',
      email: 'ava.c@example.com',
      phone: '555-0107',
      status: 'Checked-in',
      source: 'PANstrat',
      totalStays: 4,
      loyaltyTier: 'Gold',
      age: 39,
      occupation: 'Astronomer',
      homeTown: 'Shanghai, China',
      language: 'Mandarin, English',
      gender: 'Female',
      dateOfBirth: '1985-02-18',
      stayHistory: [
        {
          hotelName: 'Last Word Kalahari',
          checkInDate: format(sub(today, { days: 4 }), 'yyyy-MM-dd'),
          checkOutDate: format(add(today, { days: 1 }), 'yyyy-MM-dd'),
          roomNumber: 'Dune Villa',
          partySize: 2,
        },
      ],
      preferences: 'Enjoys star-gazing. Allergic to nuts.',
      onSiteActivity: {
        firstSeen: format(sub(today, { days: 4 }), 'yyyy-MM-dd, HH:mm'),
        lastSeen: format(sub(today, { hours: 2 }), 'yyyy-MM-dd, HH:mm'),
        connectedDevices: ['iPhone 15', 'Apple Watch Ultra'],
      },
      communicationHistory: [
        { date: format(sub(today, { days: 5 }), 'yyyy-MM-dd'), log: 'Dietary restrictions confirmed.' },
      ],
      feedback: []
    },
    {
      id: 'guest-8',
      name: 'Javier Morales',
      email: 'javier.m@example.com',
      phone: '555-0108',
      status: 'Arriving Soon',
      source: 'Manual Entry',
      totalStays: 1,
      loyaltyTier: 'Member',
      age: 31,
      occupation: 'Marketing Manager',
      homeTown: 'Madrid, Spain',
      language: 'Spanish, English',
      gender: 'Male',
      dateOfBirth: '1993-05-20',
      stayHistory: [
        {
          hotelName: 'Last Word Kitara',
          checkInDate: format(add(today, { days: 2 }), 'yyyy-MM-dd'),
          checkOutDate: format(add(today, { days: 7 }), 'yyyy-MM-dd'),
          roomNumber: '02',
          partySize: 2,
        },
      ],
      preferences: 'Honeymoon couple. Requested a private dinner setup for their arrival night.',
      onSiteActivity: {
        firstSeen: 'N/A',
        lastSeen: 'N/A',
        connectedDevices: [],
      },
      communicationHistory: [
        { date: format(sub(today, { days: 3 }), 'yyyy-MM-dd'), log: 'Confirmed honeymoon package details.' },
      ],
      feedback: []
    },
     {
      id: 'guest-9',
      name: 'Chloe Williams',
      email: 'chloe.w@example.com',
      phone: '555-0109',
      status: 'Checked-out',
      source: 'PANstrat',
      totalStays: 2,
      loyaltyTier: 'Gold',
      age: 36,
      occupation: 'Interior Designer',
      homeTown: 'Sydney, Australia',
      language: 'English',
      gender: 'Female',
      dateOfBirth: '1988-08-08',
      stayHistory: [
        {
          hotelName: 'Last Word Madikwe',
          checkInDate: format(sub(today, { days: 15 }), 'yyyy-MM-dd'),
          checkOutDate: format(sub(today, { days: 10 }), 'yyyy-MM-dd'),
          roomNumber: '10',
          partySize: 4,
          children: 2,
          pets: false,
        },
      ],
      preferences: 'Family with two young children. Prefers ground-floor rooms.',
      onSiteActivity: {
        firstSeen: format(sub(today, { days: 15 }), 'yyyy-MM-dd, HH:mm'),
        lastSeen: format(sub(today, { days: 10 }), 'yyyy-MM-dd, HH:mm'),
        connectedDevices: ['iPad Mini', 'iPhone 13', 'iPhone 13'],
      },
      communicationHistory: [
        { date: format(sub(today, { days: 9 }), 'yyyy-MM-dd'), log: 'Post-stay "Thank You" email sent.' },
      ],
      feedback: []
    },
     {
      id: 'guest-10',
      name: 'Ben Carter',
      email: 'ben.c@example.com',
      phone: '555-0110',
      status: 'Checked-in',
      source: 'Purple WiFi',
      totalStays: 1,
      loyaltyTier: 'Member',
      age: 24,
      occupation: 'Student',
      homeTown: 'Cape Town, South Africa',
      language: 'English',
      gender: 'Male',
      dateOfBirth: '2000-07-19',
      stayHistory: [
        {
          hotelName: 'Last Word Long Beach',
          checkInDate: format(sub(today, { days: 1 }), 'yyyy-MM-dd'),
          checkOutDate: format(add(today, { days: 4 }), 'yyyy-MM-dd'),
          roomNumber: '202',
          partySize: 1,
        },
      ],
      preferences: 'No preferences listed.',
      onSiteActivity: {
        firstSeen: format(sub(today, { days: 1 }), 'yyyy-MM-dd, HH:mm'),
        lastSeen: format(sub(today, { minutes: 15 }), 'yyyy-MM-dd, HH:mm'),
        connectedDevices: ['Android Phone'],
        venuesVisited: ['Long Beach Restaurant'],
      },
      communicationHistory: [],
      feedback: []
    },
    {
      id: 'guest-11',
      name: 'Olivia Garcia',
      email: 'olivia.g@example.com',
      phone: '555-0111',
      status: 'Arriving Soon',
      source: 'PANstrat',
      totalStays: 3,
      loyaltyTier: 'Gold',
      age: 45,
      occupation: 'Lawyer',
      homeTown: 'Miami, USA',
      language: 'English, Spanish',
      gender: 'Female',
      dateOfBirth: '1979-10-28',
      stayHistory: [
        {
          hotelName: 'Last Word Madikwe',
          checkInDate: format(add(today, { days: 1 }), 'yyyy-MM-dd'),
          checkOutDate: format(add(today, { days: 5 }), 'yyyy-MM-dd'),
          roomNumber: '03',
          partySize: 3,
          children: 1,
        },
      ],
      preferences: 'Prefers extra pillows and a quiet room.',
      onSiteActivity: {
        firstSeen: 'N/A',
        lastSeen: 'N/A',
        connectedDevices: [],
      },
      communicationHistory: [
        { date: format(sub(today, { days: 2 }), 'yyyy-MM-dd'), log: 'Room request acknowledged.' },
      ],
      feedback: []
    },
    {
      id: 'guest-12',
      name: 'Lucas Nguyen',
      email: 'lucas.n@example.com',
      phone: '555-0112',
      status: 'Checked-out',
      source: 'Booking.com',
      totalStays: 1,
      loyaltyTier: 'Member',
      age: 30,
      occupation: 'Data Scientist',
      homeTown: 'Ho Chi Minh City, Vietnam',
      language: 'Vietnamese, English',
      gender: 'Male',
      dateOfBirth: '1994-12-01',
      stayHistory: [
        {
          hotelName: 'Last Word Franschhoek',
          checkInDate: format(sub(today, { days: 7 }), 'yyyy-MM-dd'),
          checkOutDate: format(sub(today, { days: 4 }), 'yyyy-MM-dd'),
          roomNumber: '09',
          partySize: 2,
        },
      ],
      preferences: 'Requested information on hiking trails.',
      onSiteActivity: {
        firstSeen: format(sub(today, { days: 7 }), 'yyyy-MM-dd, HH:mm'),
        lastSeen: format(sub(today, { days: 4 }), 'yyyy-MM-dd, HH:mm'),
        connectedDevices: ['Garmin Watch', 'iPhone 12'],
      },
      communicationHistory: [
        { date: format(sub(today, { days: 3 }), 'yyyy-MM-dd'), log: 'Post-stay "Thank You" email sent.' },
      ],
      feedback: []
    },
    {
      id: 'prospect-1',
      name: 'Fatima Al-Jamil',
      email: 'fatima.aj@example.com',
      phone: '555-0113',
      status: 'Prospect',
      source: 'Tourism Expo',
      totalStays: 0,
      loyaltyTier: 'Member',
      age: 38,
      occupation: 'Doctor',
      homeTown: 'Dubai, UAE',
      language: 'Arabic, English',
      gender: 'Female',
      dateOfBirth: '1986-07-22',
      stayHistory: [],
      preferences: 'Inquired about family-friendly safari packages and accessibility for elderly parents.',
      onSiteActivity: { firstSeen: 'N/A', lastSeen: 'N/A', connectedDevices: [] },
      communicationHistory: [
        { date: format(sub(today, { weeks: 2 }), 'yyyy-MM-dd'), log: 'Met at World Travel Market expo.' },
        { date: format(sub(today, { weeks: 1 }), 'yyyy-MM-dd'), log: 'Sent follow-up email with family package brochure.' },
      ],
      feedback: []
    },
    {
      id: 'prospect-2',
      name: 'David Chen',
      email: 'david.c@example.com',
      phone: '555-0114',
      status: 'Prospect',
      source: 'Manual Entry',
      totalStays: 0,
      loyaltyTier: 'Member',
      age: 45,
      occupation: 'Venture Capitalist',
      homeTown: 'Singapore',
      language: 'Mandarin, English',
      gender: 'Male',
      dateOfBirth: '1979-05-14',
      stayHistory: [],
      preferences: 'Referred by Eleanor Vance. Interested in exclusive-use villas for a corporate retreat.',
      onSiteActivity: { firstSeen: 'N/A', lastSeen: 'N/A', connectedDevices: [] },
      communicationHistory: [
        { date: format(sub(today, { days: 5 }), 'yyyy-MM-dd'), log: 'Initial inquiry received via email.' },
      ],
      feedback: []
    },
    {
      id: 'prospect-3',
      name: 'Isabella Johansson',
      email: 'isabella.j@example.com',
      phone: '555-0115',
      status: 'Prospect',
      source: 'Purple WiFi',
      totalStays: 0,
      loyaltyTier: 'Member',
      age: 29,
      occupation: 'Freelance Writer',
      homeTown: 'Stockholm, Sweden',
      language: 'Swedish, English',
      gender: 'Female',
      dateOfBirth: '1995-03-10',
      stayHistory: [],
      preferences: 'Connected to WiFi at Last Word Constantia while visiting the restaurant. Downloaded a wine-tasting guide.',
      onSiteActivity: {
        firstSeen: format(sub(today, { days: 20, hours: 4 }), 'yyyy-MM-dd, HH:mm'),
        lastSeen: format(sub(today, { days: 20, hours: 2 }), 'yyyy-MM-dd, HH:mm'),
        connectedDevices: ['iPhone 14 Pro'],
        venuesVisited: ['Constantia Restaurant'],
      },
      communicationHistory: [
        { date: format(sub(today, { days: 19 }), 'yyyy-MM-dd'), log: 'Added to newsletter for local events and offers.' },
      ],
      feedback: []
    },
  ];
}
